### ISSUE TITLE
Scene 3 - Dark Room (Torchlight Effect Feature)

### ISSUE THREAD

**Issue by KelvenH** [alissatroiano/The-Grim-Repo#13]
- barely visible image revealed with cursor acting as phone torchlight
- multiple interactive elements when clicked upon open in modal windows
- 1 acts as link to next scene (activates opening of secret doorway in bookcase)
- 1 acts as additional 'help' for future (e.g. matches?)
- 1 Easter Egg (book title)
- others random humours / horror book titles or other objects
- timer function on life of phone which is displayed in nav but terminates light function when time has run out)

**Comment by auxfuse** [comment]
Closing to suit PR #34
