### ISSUE TITLE
Deafult file structure:

### ISSUE THREAD

**Issue by auxfuse** [alissatroiano/The-Grim-Repo#4]
* include base index.html
* should include any relative imports...bootstrap in index head
* include base stlye.css inside css directory
* include base main.js inside js directory
* assets folder to house css/js/images
* docs folder to house wireframes/planning docs etc
* README in root (already there)
* default gitignore (to ignore vscode default directories etc)

**Comment by alissatroiano** [comment]
Set up some of this for you (bI think you're just adding any imports and reviewing lol.. hope that's ok!

**Comment by auxfuse** [comment]
Closing to suit PR #9
